# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

env:
  artifact_name: webapp-${{github.run_number}}.zip
  s3_bucket_name: codedeploy-davebhavin-me
  aws_region: ${{ secrets.AWS_AMI_REGION }}
  cd_app_name: ${{ secrets.cd_app_name }}
  cd_app_deploy_gname: ${{ secrets.cd_app_deploy_gname }}
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v2
    - run:
        zip -r $artifact_name
        ls -la
        mkdir cd_artifact
        mv $artifact_name cd_artifact/