# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

env:
  artifact_name: webapp-${{github.run_number}}.zip
  s3_bucket_name: codedeploy-davebhavin-me
  AWS_AMI_REGION: ${{ secrets.AWS_AMI_REGION }}
  CD_APP_NAME: ${{ secrets.CD_APP_NAME }}
  D_APP_DEPLOY_GNAME: ${{ secrets.D_APP_DEPLOY_GNAME }}
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: copy to s3
      run: |
        mkdir cd_artifact
        cd cd_artifact
        cp ../*.json .
        cp ../*.js .
        cp ../*.md .
        cp -r ../src .
        cp -r ../test .
        cp -r ../.github/workflows .
        cp -r ../.git .
        cp -r ../script .
        cp ../*.yml .
        touch .env
        zip -r webapp .
        ls -a
        aws s3 cp webapp.zip s3://${bucket_name}
        echo 'upload to s3 done'