# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

env:
  artifact_name: webapp-${{github.run_number}}.zip
  s3_bucket_name: codedeploy-davebhavin-me
  AWS_AMI_REGION: ${{ secrets.AWS_AMI_REGION }}
  CD_APP_NAME: ${{ secrets.CD_APP_NAME }}
  D_APP_DEPLOY_GNAME: ${{ secrets.D_APP_DEPLOY_GNAME }}
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v2
    - run:
        zip -r webapp
        ls -la
        mkdir cd_artifact
        mv webapp cd_artifact/